version: 2
enable-beta-ecosystems: true  # for bun
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "07:00"
    groups:
      # group all development dependencies
      dev-dependencies:
        dependency-type: "development"
      # group all minor/patch updates (except major)
      all-non-major:
        patterns: ["*"]
        update-types: ["minor", "patch"]
    assignees:
      - "huuthienp"
