[functions]
  node_bundler = 'esbuild'

[functions.'init-reminder-*']
  schedule = '0 20 * * *'
  # once a day, at 20:00 (8 PM) UTC
  # the workflows on Qualtrics can be delayed (different time zone)

[[redirects]]
  from = '/api/recovery'
  to = '/.netlify/functions/recovery'
  status = 200

[[redirects]]
  from = '/archive/*'
  to = '/404.html'
  status = 301
  force = true

[[redirects]]
  from = '/*'
  to = '/404.html'
  status = 301
